### ISSUE TITLE
bug: save draft as shipment

### ISSUE THREAD

**Issue by mikkel1ea** [equinor/chemcom-api#130]
If you create a draft from the shipment form, and then try to submit the draft and make it into a shipment the status remains the same as shipment.

**Comment by spatrE01** [comment]
https://github.com/user-attachments/assets/0f8c1568-bcf5-4ae8-8c05-46c1a96f05ac
I tested this issue on local by pointing on dev backend and my observations are - 
User is able to 
1. Create a draft
2. Edit and submit the draft
3. Fetch the Registered Shipment and the status is getting updated to "Submitted"

A screen recorded video is attached.

**Comment by vehecap** [comment]
Seems like you can close this issue then @ashukequinor
