### ISSUE TITLE
feat(chemical history): Watervolumes, name of shipment & date of shipment to datatable

### ISSUE THREAD

**Issue by mikkel1ea** [equinor/chemcom-api#180]
Message from user:

"Sture has received a mandate from the Environmental Directorate to account for chemicals that may contribute to emissions from the facility. In this regard, we would need an Excel file with data from Chemcom with reported data in GOP and OTS for the years 2018 - 2024 so that we can correlate chemicals sent through the pipeline with measured emissions at Sture. Unfortunately, we are unable to include the date when extracting data directly from the Chemcom application ourselves, which is why we need help with this. It would also be good to have the volumes of water that have been sent ashore along with the chemicals."

Where: https://chemcom.equinor.com/c4d2d827-48e6-45a8-9fb4-dbd8e7a54a67/chemicalHistory (Chemical history on all onshore innstalations)
What: Adding the following data connected to the chemicals in the above data table: Name of shipment, Date of shipment & water volumes that was sent in the shipment where the chemical is registered from.

**Comment by bonyfusbouvet** [comment]
@mikkel1ea @Jone-Torgersen the change should be on dev now.
