### ISSUE TITLE
fix: change how a form is saved as draft

### ISSUE THREAD

**Issue by FredrikMWold** [equinor/chemcom-api#24]
The user should be able to save an unfinished form as a draft.

This functionality already exist in the backend but the api endpoints need work.
When a form is saved as a draft it uses the endpoint `https://chemdec-dev.azurewebsites.net/api/shipment/offshore/change`
Which is the same endpoint that is used to update an existing form.
Need a separate endpoint or  a flag to set in the `https://chemdec-dev.azurewebsites.net/api/shipment/offshore/submit` endpoint.

**Comment by vehecap** [comment]
@Jone-Torgersen @bonyfusbouvet Is this still relevant for the API? Seems the issue has been closed in the frontend repo.

**Comment by Jone-Torgersen** [comment]
> [@Jone-Torgersen](https://github.com/Jone-Torgersen) [@bonyfusbouvet](https://github.com/bonyfusbouvet) Is this still relevant for the API? Seems the issue has been closed in the frontend repo.

This has sort of been redone with the implementation of the multi-step form, so I don't think it is relevant anymore.
