### ISSUE TITLE
feat: get emails from azure groups

### ISSUE THREAD

**Issue by mikkel1ea** [equinor/chemcom-api#97]
Currently in the system who gets what email has two different setups. For notification emails going to onshore or offshore installations the emails are fetched from SQL storage. For chemical responsible notifications it's taken from a config file which references some emails stored in keyvault. 

None of these approaches are ideal, instead it should have some logic for which azure groups to fetch the correct email adresses. So that there isnt a static source of who gets emails, but that it is shaped by who has the different roles.

**Comment by Jone-Torgersen** [comment]
Just got a feature request from a user. They want to be able to manage the list of email recipients themselves, as they are one of the main access-granters to chemcom.  When they add or remove someone's access to a platform, they now have to send us an email with requested changes to the email recipient list. 

The suggestion was for a way to manage the list in the UI of the chemcom solution itself,  but if we can implement a way of doing it through role assignments for them, that would probably be sufficient.

**Comment by mikkel1ea** [comment]
It's something we'll have to check up with them on. I feel like the best option would be that who gets emails is defined by role memberships. E.g. if you're a member of Sture you get a notification when something happens at Sture and so on.  And thus no administration is needed and people are removed automatically (when role is expires).
But, if not everyone should get a notification within a group then we'll have to have a look at a UI solution where this can be administered more spesifically.
